feat: update goreleaser for prober
abcxyz/pmap pull request #161
Opened 2023-08-01 21:36 UTC by sailorlqh

2023-08-01 21:40 UTC, capri-xiyue commented on prober/prober.dockerfile
> +ENTRYPOINT ["./pmap-prober"]
Unlike JVS, you are no longer using simple bash for probder, do you need this?

2023-08-01 21:44 UTC, yolocs requested changes

2023-08-01 21:44 UTC, yolocs commented on .goreleaser.docker.yaml
> +      - '--label=org.opencontainers.image.description=Privacy data mapping tool'
Update description

2023-08-01 21:44 UTC, yolocs commented on .goreleaser.docker.yaml
> +      - '--label=org.opencontainers.image.description=Privacy data mapping tool'
Update description

2023-08-01 21:44 UTC, yolocs commented on prober/prober.dockerfile
> +FROM cgr.dev/chainguard/bash:latest
We should use distroless image here.

2023-08-02 20:47 UTC, capri-xiyue commented on prober/prober.dockerfile
> +FROM gcr.io/distroless/base-debian11:latest
Why use base-debian, does static work here https://github.com/abcxyz/jvs/blob/main/Dockerfile

2023-08-02 20:48 UTC, yolocs requested changes

2023-08-02 20:48 UTC, yolocs commented on prober/prober.dockerfile
> +FROM gcr.io/distroless/base-debian11:latest
Should be `gcr.io/distroless/static`

2023-08-02 21:43 UTC, yolocs approved these changes
Did you try the prober out manually?

2023-08-02 22:02 UTC, merged